### ISSUE TITLE
Vraagtekens in de room naam

### ISSUE THREAD

**Issue by julesmons** [dionkoeze/livemood#2]
Hallo Dion,

Alleereerst positieve feedback voor LiveMood.
Wel een klein buggje: Wanneer je een vraagteken in je roomnaam zet kun je er niet in.
Dat heeft met de URL te maken (Get Parameters).

Wellicht op te lossen door dat karakter te blokeren bij het aanmaken.

Vriendelijke groet,

Jules Mons

**Comment by dionkoeze** [comment]
Good catch!

De room URI wordt nu encoded gebruikt, dus nu kan je ook rooms met een vraagteken erin aanmaken :)

Dank!
